# Generated by Django 4.1.7 on 2023-03-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('endereço', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('data_nascimento', models.CharField(max_length=8)),
                ('situação', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GPP',
        ),
    ]
