# Generated by Django 4.1.7 on 2023-03-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_funcionarios_delete_gpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('num_contrato', models.CharField(max_length=255)),
                ('tipo_serviço', models.CharField(max_length=255)),
                ('orgão', models.CharField(max_length=255)),
                ('razão_social', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('vigencia', models.CharField(max_length=15)),
                ('data_abertura', models.CharField(max_length=8)),
                ('situação', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('pode_editar', 'editar informações do projeto'),),
            },
        ),
    ]
