# Generated by Django 4.1.7 on 2023-03-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_projetos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetos',
            options={},
        ),
    ]
