# Generated by Django 4.1.7 on 2023-03-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_projetos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='email',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='senha',
            new_name='cidade',
        ),
    ]
