# Generated by Django 4.1.7 on 2023-03-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_email_funcionarios_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='data_nascimento',
            field=models.CharField(max_length=20),
        ),
    ]
