# Generated by Django 4.1.7 on 2023-03-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_funcionarios_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='situação',
            field=models.CharField(max_length=10),
        ),
    ]
