# Generated by Django 4.1.7 on 2023-03-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_funcionarios_cpf_alter_funcionarios_situação'),
    ]

    operations = [
        migrations.CreateModel(
            name='fornecedores_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=255)),
                ('razão_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=255)),
                ('endereço', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
