# Generated by Django 4.1.7 on 2023-03-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_fornecedores_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores_clientes',
            name='pais',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
    ]
