# Generated by Django 4.1.7 on 2023-03-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_projetos_orgão_remove_projetos_razão_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='orgão',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='razão_social',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
