# Generated by Django 4.1.7 on 2023-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_projetos_orgão_projetos_razão_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordem_serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnumero_os', models.CharField(max_length=255)),
                ('situação', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='descrição',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='local',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='nome_projeto',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='num_contrato',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='orgão',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='razão_social',
        ),
        migrations.AddField(
            model_name='projetos',
            name='GP_responsavel',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='cnpj_fk',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='contratante',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='email_GP_responsavel',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='n_contrato',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='pontos_função',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='pontos_função_unit',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='qtd_horas_os',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='valor_global_contrato',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='valor_os_unit',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='valor_total',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetos',
            name='data_abertura',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='situação',
            field=models.CharField(choices=[('1', 'Desenvolvimento Softwares e Aplicativos'), ('2', 'Serviços Suporte à Infraestrutura de Software'), ('3', 'Armazenamento de Dados'), ('4', 'Proteção de Dados'), ('5', 'Segurança Cibernética'), ('6', 'Computação em Nuvem')], max_length=7),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='tipo_serviço',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=7),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='vigencia',
            field=models.CharField(max_length=20),
        ),
    ]
