# Generated by Django 4.1.7 on 2023-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_ordem_serviço_remove_projetos_descrição_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='valor_os_total',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
