# Generated by Django 4.1.7 on 2023-03-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_projetos_valor_os_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='GP_responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='cnpj_fk',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='contratante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='data_abertura',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='email_GP_responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='n_contrato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='pontos_função',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='pontos_função_unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='qtd_horas_os',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='situação',
            field=models.CharField(choices=[('1', 'Desenvolvimento Softwares e Aplicativos'), ('2', 'Serviços Suporte à Infraestrutura de Software'), ('3', 'Armazenamento de Dados'), ('4', 'Proteção de Dados'), ('5', 'Segurança Cibernética'), ('6', 'Computação em Nuvem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='tipo_serviço',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor_global_contrato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor_os_total',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor_os_unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor_total',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='vigencia',
            field=models.CharField(max_length=100),
        ),
    ]
