# Generated by Django 4.1.7 on 2023-03-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_projetos_gp_responsavel_alter_projetos_cnpj_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='situação',
            field=models.CharField(choices=[('1', 'Desenvolvimento Softwares e Aplicativos'), ('2', 'Serviços Suporte à Infraestrutura de Software'), ('3', 'Armazenamento de Dados'), ('4', 'Proteção de Dados'), ('5', 'Segurança Cibernética'), ('6', 'Computação em Nuvem')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='tipo_serviço',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=100),
        ),
    ]
