# Generated by Django 4.1.7 on 2023-03-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_projetos_situação_alter_projetos_tipo_serviço'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem_serviço',
            name='nnumero_os',
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='abertura',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='cnpj_fk',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='codigo_os',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='contratante',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='descrição',
            field=models.TextField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='n_contrato',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='pontos_função',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='qtd_horas',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='tipo_serviço',
            field=models.CharField(choices=[('1', 'Desenvolvimento Softwares e Aplicativos'), ('2', 'Serviços Suporte à Infraestrutura de Software'), ('3', 'Armazenamento de Dados'), ('4', 'Proteção de Dados'), ('5', 'Segurança Cibernética'), ('6', 'Computação em Nuvem')], default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordem_serviço',
            name='vencimento',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetos',
            name='situação',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='tipo_serviço',
            field=models.CharField(choices=[('1', 'Desenvolvimento Softwares e Aplicativos'), ('2', 'Serviços Suporte à Infraestrutura de Software'), ('3', 'Armazenamento de Dados'), ('4', 'Proteção de Dados'), ('5', 'Segurança Cibernética'), ('6', 'Computação em Nuvem')], max_length=100),
        ),
    ]
