# Generated by Django 4.1.7 on 2023-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_projetos_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='relatorio',
        ),
    ]
