# Generated by Django 4.1.7 on 2023-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_relatorios_remove_projetos_relatorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relatorios',
        ),
        migrations.AddField(
            model_name='projetos',
            name='relatorio',
            field=models.FileField(default='null', upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
