# Generated by Django 4.1.7 on 2023-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_projetos_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_serviço',
            name='situação',
            field=models.CharField(max_length=20),
        ),
    ]
